### ISSUE TITLE
TypeError：unsupported operand type(s) for +=: 'NoneType' and 'Tensor'

### ISSUE THREAD

**Issue by hiroi-sora** [JunyiZhu-AI/surrogate_model_extension#1]
Thank you for sharing this code, it's very enlightening.

The code on [Adversary/adversary.py #L84](https://github.com/JunyiZhu-AI/surrogate_model_extension/blob/89a46a2681d73bd828fd01d73ae39ffd8b68f279/sme/Adversary/adversary.py#L84) is:
```python
alpha_opti.zero_grad()
```

In PyTorch v1.x versions, the [default argument](https://pytorch.org/docs/1.11/generated/torch.optim.Optimizer.zero_grad.html?highlight=torch%20optim%20optimizer%20zero_grad#torch.optim.Optimizer.zero_grad) for `zero_grad()` is `set_to_none=False`. However, in version 2, the [default argument](https://pytorch.org/docs/2.0/generated/torch.optim.Optimizer.zero_grad.html?highlight=torch%20optim%20optimizer%20zero_grad#torch.optim.Optimizer.zero_grad) changed to `set_to_none=True`. If we are forced to use the newer version of PyTorch for experiments, an error will occur:
```
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'Tensor'
```

In this case, manually specifying the argument will resolve the issue:
```python
alpha_opti.zero_grad(False)
```

**Comment by JunyiZhu-AI** [comment]
Thank you very much for the feedback. I have updated the code accordingly.
